#!/bin/bash
coproc java Client

echo SHOW TABLES >&${COPROC[1]}
PAUSE
cat <&${COPROC[0]}
PAUSE
echo DESC student >&${COPROC[1]}
PAUSE
cat <&${COPROC[0]}
PAUSE
echo DESC faculty >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo INSERT INTO STUDENT (`FIRSTNAME`, `SECONDNAME`, `UUID`) VALUES ('GAGAN', 'SHARMA', '19114032') >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo INSERT INTO STUDENT (`FIRSTNAME`, `SECONDNAME`, `UUID`) VALUES ('SHLOK', 'GOYAL', '19114002') >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo INSERT INTO STUDENT (`FIRSTNAME`, `SECONDNAME`, `UUID`) VALUES ('JITESH', 'JAIN', '19114000') >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo INSERT INTO STUDENT (`FIRSTNAME`, `SECONDNAME`, `UUID`) VALUES ('R', 'CHINMAY', '19114003') >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo SELECT * FROM STUDENT >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE
echo INSERT INTO STUDENT (`FIRSTNAME`, `SECONDNAME`, `UUID`) VALUES ('R', 'CHINMAY', '19114003') >&${COPROC[1]}
cat <&${COPROC[0]}
PAUSE